# Generated by Django 5.2.6 on 2025-09-19 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_contact_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
